Document functions
eqlabs/starknet-multisig pull request #39
Opened 2022-07-25 12:56 UTC by microbecode

Follows the documentation standard: https://github.com/CairOpen/SIMPs/blob/main/SIMPS/simp-4.md

2022-07-25 12:57 UTC, JaniAnttonen commented
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>69ea4f1</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-dxfz2pfab-equilibriumco.vercel.app'>https://starknet-multisig-dxfz2pfab-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/7K63jWZ6Fg7kyxahXaKGGeoMmeBH'>https://vercel.com/equilibriumco/starknet-multisig/7K63jWZ6Fg7kyxahXaKGGeoMmeBH</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2732441924)

2022-07-26 07:30 UTC, JaniAnttonen commented
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>7376259</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-js85c50t3-equilibriumco.vercel.app'>https://starknet-multisig-js85c50t3-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/F14GGv2mNMEexidEe9xXXwesumvF'>https://vercel.com/equilibriumco/starknet-multisig/F14GGv2mNMEexidEe9xXXwesumvF</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2737757726)

2022-07-26 07:45 UTC, JaniAnttonen commented
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>6f86647</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-j1pk4a8s1-equilibriumco.vercel.app'>https://starknet-multisig-j1pk4a8s1-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/EmdbR6SQmtCKU8n5hxhwDKNtPGw7'>https://vercel.com/equilibriumco/starknet-multisig/EmdbR6SQmtCKU8n5hxhwDKNtPGw7</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2737839515)

2022-07-26 09:04 UTC, JaniAnttonen requested changes
Some small nitpicks :)

2022-07-26 09:06 UTC, microbecode commented on contracts/contracts/Multisig.cairo
> +# @param threshold: What is the new threshold
Sorry, what should be changed here?

2022-07-26 09:08 UTC, microbecode commented on contracts/contracts/Multisig.cairo
> +# @param threshold: Threshold to check
Hmm, I disagree. The given threshold is not a required threshold. We are checking the given threshold that it's valid based on some other criteria.

2022-07-26 09:08 UTC, microbecode commented on contracts/contracts/Multisig.cairo
> +# @param signers_len: Amount of signers in the multisig
I disagree here as well. We're not setting here anything, we are only checking validity.

2022-07-26 09:09 UTC, microbecode commented on contracts/contracts/Multisig.cairo
> +# @param nonce: Nonce to check
I disagree here as well. We're not setting here anything, we are only checking validity.

2022-07-26 09:10 UTC, JaniAnttonen commented on contracts/contracts/Multisig.cairo
> +# @param threshold: What is the new threshold
Just remove the question IMO

2022-07-26 09:19 UTC, microbecode commented on contracts/contracts/Multisig.cairo
> +# @param threshold: What is the new threshold
Ah, good point. Fixed - also for all other events.

2022-07-26 09:20 UTC, JaniAnttonen approved these changes

2022-07-26 09:20 UTC, JaniAnttonen commented
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f802cc6</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://starknet-multisig-cgcsmf2ph-equilibriumco.vercel.app'>https://starknet-multisig-cgcsmf2ph-equilibriumco.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/equilibriumco/starknet-multisig/8Mh2mF9VJNPbZQgTQBkFbKHZ4krW'>https://vercel.com/equilibriumco/starknet-multisig/8Mh2mF9VJNPbZQgTQBkFbKHZ4krW</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/eqlabs/starknet-multisig/actions/runs/2738396369)

2022-07-26 09:20 UTC, merged